// Auto-generated product image map (name -> /products/...). Filenames derived from optimized EN product titles.
// Source: 产品箱规重量(1).xlsx
export const productImages = {
  "500田园": "/products/500ml-stainless-steel-double-wall-insulated-pastoral-bottle-wholesale-factory-oem-odm.png",
  "750田园": "/products/750ml-stainless-steel-double-wall-insulated-pastoral-bottle-wholesale-factory-oem-odm.png",
  "1000田园": "/products/1000ml-stainless-steel-double-wall-insulated-pastoral-bottle-wholesale-factory-oem-odm.png",
  "500直杯": "/products/500ml-stainless-steel-double-wall-insulated-straight-bottle-wholesale-factory-oem-odm.jpeg",
  "750直杯": "/products/750ml-stainless-steel-double-wall-insulated-straight-bottle-wholesale-factory-oem-odm.png",
  "1000直杯": "/products/1000ml-stainless-steel-double-wall-insulated-straight-bottle-wholesale-factory-oem-odm.jpeg",
  "750菱形": "/products/750ml-stainless-steel-double-wall-insulated-diamond-bottle-wholesale-factory-oem-odm.png",
  "1000菱形": "/products/1000ml-stainless-steel-double-wall-insulated-diamond-bottle-wholesale-factory-oem-odm.png",
  "750葫芦": "/products/750ml-stainless-steel-double-wall-insulated-gourd-bottle-wholesale-factory-oem-odm.png",
  "1000葫芦": "/products/1000ml-stainless-steel-double-wall-insulated-gourd-bottle-wholesale-factory-oem-odm.png",
  "750牛奶瓶": "/products/750ml-stainless-steel-double-wall-insulated-milk-bottle-wholesale-factory-oem-odm.png",
  "1000牛奶瓶": "/products/1000ml-stainless-steel-double-wall-insulated-milk-bottle-wholesale-factory-oem-odm.png",
  "750平底可乐瓶": "/products/750ml-stainless-steel-double-wall-insulated-cola-bottle-wholesale-factory-oem-odm.png",
  "1000平底可乐瓶": "/products/1000ml-stainless-steel-double-wall-insulated-cola-bottle-wholesale-factory-oem-odm.png",
  "1000大肚杯": "/products/1000ml-stainless-steel-double-wall-insulated-round-tumbler-wholesale-factory-oem-odm.png",
  "直杯塑料盖": "/products/stainless-steel-double-wall-insulated-straight-cup-lid-wholesale-factory-oem-odm.png",
  "腰型塑料盖": "/products/stainless-steel-double-wall-insulated-waist-lid-wholesale-factory-oem-odm.png",
  "美式葫芦杯": "/products/stainless-steel-double-wall-insulated-gourd-bottle-wholesale-factory-oem-odm.png",
  "1000单层压底可乐瓶": "/products/1000ml-stainless-steel-double-wall-insulated-single-wall-bottle-wholesale-factory-oem-odm.png",
  "750单层压底可乐瓶": "/products/750ml-stainless-steel-double-wall-insulated-single-wall-bottle-wholesale-factory-oem-odm.png",
  "500单层压底可乐瓶": "/products/500ml-stainless-steel-double-wall-insulated-single-wall-bottle-wholesale-factory-oem-odm.png",
  "500小口瓶": "/products/500ml-stainless-steel-double-wall-insulated-narrow-mouth-bottle-wholesale-factory-oem-odm.png",
  "750小口瓶": "/products/750ml-stainless-steel-double-wall-insulated-narrow-mouth-bottle-wholesale-factory-oem-odm.png",
  "易拉罐": "/products/stainless-steel-double-wall-insulated-can-style-bottle-wholesale-factory-oem-odm.png",
  "咖啡杯": "/products/stainless-steel-double-wall-insulated-coffee-cup-wholesale-factory-oem-odm.png",
  "蛋杯": "/products/stainless-steel-double-wall-insulated-egg-cup-wholesale-factory-oem-odm.png",
  "350美式大口": "/products/350ml-stainless-steel-double-wall-insulated-wide-mouth-bottle-wholesale-factory-oem-odm.png",
  "500美式大口": "/products/500ml-stainless-steel-double-wall-insulated-wide-mouth-bottle-wholesale-factory-oem-odm.jpeg",
  "600美式大口": "/products/600ml-stainless-steel-double-wall-insulated-wide-mouth-bottle-wholesale-factory-oem-odm.png",
  "750美式大口": "/products/750ml-stainless-steel-double-wall-insulated-wide-mouth-bottle-wholesale-factory-oem-odm.png",
  "500真空可乐瓶": "/products/500ml-stainless-steel-vacuum-insulated-cola-bottle-wholesale-factory-oem-odm.jpeg",
  "750真空可乐瓶": "/products/750ml-stainless-steel-vacuum-insulated-cola-bottle-wholesale-factory-oem-odm.jpeg",
  "1000真空可乐瓶": "/products/1000ml-stainless-steel-vacuum-insulated-cola-bottle-wholesale-factory-oem-odm.jpeg",
  "3代4.0汽车杯": "/products/stainless-steel-double-wall-insulated-car-cup-gen-3-wholesale-factory-oem-odm.png",
  "2代4.0汽车杯": "/products/stainless-steel-double-wall-insulated-car-cup-gen-2-wholesale-factory-oem-odm.png",
  "1代4.0汽车杯": "/products/stainless-steel-double-wall-insulated-car-cup-gen-1-wholesale-factory-oem-odm.png",
  "一杯三盖": "/products/stainless-steel-double-wall-insulated-3-in-1-bottle-wholesale-factory-oem-odm.png",
  "温度杯": "/products/stainless-steel-double-wall-insulated-temp-display-bottle-wholesale-factory-oem-odm.jpeg",
  "350子弹头": "/products/350ml-stainless-steel-double-wall-insulated-bullet-bottle-wholesale-factory-oem-odm.jpeg",
  "500子弹头": "/products/500ml-stainless-steel-double-wall-insulated-bullet-bottle-wholesale-factory-oem-odm.png",
  "1000子弹头": "/products/1000ml-stainless-steel-double-wall-insulated-bullet-bottle-wholesale-factory-oem-odm.png",
  "750小蛮腰": "/products/750ml-stainless-steel-double-wall-insulated-slim-waist-bottle-wholesale-factory-oem-odm.png",
  "500小蛮腰": "/products/500ml-stainless-steel-double-wall-insulated-slim-waist-bottle-wholesale-factory-oem-odm.png",
};
